"""
Django settings for parcelaireKG project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from celery.schedules import crontab
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# ─────────────────────────────────────────────────────────────────────────
# Sécurité : les valeurs sensibles sont lues depuis .env (python-decouple).
# Un fallback "django-insecure-…" est conservé UNIQUEMENT pour le bootstrap
# en local. En production l'env DJANGO_ENV=prod + une vraie SECRET_KEY
# obligent à renseigner ces variables.
# ─────────────────────────────────────────────────────────────────────────
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-CHANGE-ME-9uzaef-rpxlqoxg!juy_7x3z*a9!y7%mhtajqaamyp9x(#0qr8",
)
DEBUG = config("DEBUG", default=True, cast=bool)


def _csv(value: str) -> list[str]:
    """Convertit "a,b , c" en ["a", "b", "c"] en supprimant les blancs."""
    return [item.strip() for item in (value or "").split(",") if item.strip()]


ALLOWED_HOSTS = _csv(config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,flow.datarium-dev.com,www.flow.datarium-dev.com",
))

CSRF_TRUSTED_ORIGINS = _csv(config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://flow.datarium-dev.com,http://flow.datarium-dev.com",
))

# En production on durcit automatiquement, sauf si désactivé explicitement.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "SAMEORIGIN"
if not DEBUG:
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.gis',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_framework',
    'rest_framework.authtoken',
    'import_export',
    'mathfilters',
    'django_select2',
    'djmoney',
    'tinymce',
    # 'simple_history',
    # 'num2words',
    'django_filters',
    # 'qr_code',
    # 'notifications',
    "channels",
    'weasyprint',
    "csp",
    'drf_spectacular',
    'corsheaders',
    "project",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]

ROOT_URLCONF = 'ProjectFlow.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.context_processors.devflow_notifications',
                'project.context_processors.devflow_rbac',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectFlow.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
SITE_ID = 1

USE_THOUSAND_SEPARATOR=True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# NOTE — STATICFILES_STORAGE est désormais déclaré dans STORAGES["staticfiles"]
# plus bas. Django 4.2+ refuse d'avoir les deux paramètres simultanément
# (cf. ImproperlyConfigured: "STATICFILES_STORAGE/STORAGES are mutually exclusive").
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Routing : tâches d'enregistrement sur queue dédiée 'recordings'
# (workload lourd, ne doit pas bloquer les emails/notifications)
CELERY_TASK_ROUTES = {
    "project.tasks.process_recording_task": {"queue": "recordings"},
    "project.tasks.finalize_recording_task": {"queue": "recordings"},
}

CELERY_BEAT_SCHEDULE = {
    # Balayage de toutes les tâches DevFlow 2x/jour pour envoyer
    # automatiquement des relances aux assignees et notifier les PM.
    # Heures locales : 9h00 (matin) et 16h00 (après-midi) Africa/Abidjan.
    "task-reminder-morning-sweep": {
        "task": "project.tasks.run_task_reminder_sweep",
        "schedule": crontab(hour=9, minute=0),
    },
    "task-reminder-afternoon-sweep": {
        "task": "project.tasks.run_task_reminder_sweep",
        "schedule": crontab(hour=16, minute=0),
    },
    # Phase 3 — PR16 : Budget V2
    # 5h00 : recalcule EAC + Cost Variance avant le scan d'alertes
    "recompute-project-eac-sweep": {
        "task": "project.tasks.recompute_project_eac_sweep",
        "schedule": crontab(hour=5, minute=0),
    },
    # 6h00 : détecte les dépassements et notifie les PM (anti-spam 24h)
    "scan-budget-overruns": {
        "task": "project.tasks.scan_budget_overruns",
        "schedule": crontab(hour=6, minute=0),
    },
    # Phase 5 — PR21 : Digest quotidien des notifications
    # 8h00 : récap email pour les users avec notify_frequency=DAILY
    "send-daily-notification-digest": {
        "task": "project.tasks.send_daily_notification_digest",
        "schedule": crontab(hour=8, minute=0),
    },
    # PR-MEET-2 : génère quotidiennement les occurrences futures des
    # séries de réunions actives, horizon de 60 jours glissants.
    "generate-meeting-occurrences-sweep": {
        "task": "project.tasks.generate_meeting_occurrences_sweep",
        "schedule": crontab(hour=4, minute=0),
    },
    # PR-MEET-8 : rappels réunion (toutes les heures)
    "send-meeting-reminders-sweep": {
        "task": "project.tasks.send_meeting_reminders_sweep",
        "schedule": crontab(minute=15),  # à chaque h+15
    },
    # Phase 5 — PR22 : Rapports IA hebdomadaires
    # Lundi 6h : génère le rapport semaine N-1 pour chaque projet actif
    "generate-project-weekly-reports": {
        "task": "project.tasks.generate_project_weekly_reports",
        "schedule": crontab(hour=6, minute=0, day_of_week=1),
    },
    # PR24 — Purge audit log (rétention 90j)
    # Dimanche 3h : nettoie les vieux logs sécurité
    "purge-old-security-logs": {
        "task": "project.tasks.purge_old_security_logs",
        "schedule": crontab(hour=3, minute=0, day_of_week=0),
    },
}

# Paramètres du moteur de relance (surchargeable via env)
TASK_REMINDER_COOLDOWN_HOURS = int(os.getenv("TASK_REMINDER_COOLDOWN_HOURS", "10"))
TASK_STALE_DAYS = int(os.getenv("TASK_STALE_DAYS", "2"))
TASK_DUE_SOON_DAYS = int(os.getenv("TASK_DUE_SOON_DAYS", "3"))

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Abidjan"

# =========================================================================
# Celery — durcissement Phase 0 (PR6)
# =========================================================================
# Sans ces options, une tâche acquittée mais non encore terminée disparaît si
# le worker reçoit un SIGKILL (OOM, redéploiement brutal) → email perdu,
# rapport non généré, mise à jour budget partielle.
#
# Réf : https://docs.celeryq.dev/en/stable/userguide/configuration.html

# Acquitte la tâche APRÈS exécution réussie (au lieu de "before"). Doublonne
# l'idempotence côté tâche (déjà OK pour nos tasks de mail + AI proposal),
# mais garantit qu'une tâche tuée à mi-chemin sera redonnée à un autre worker.
CELERY_TASK_ACKS_LATE = True

# Couplé à acks_late : si le worker meurt pendant l'exécution, la tâche est
# requeuée. Sans cela, elle resterait coincée en "running" indéfiniment.
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Marque la tâche comme STARTED dès qu'un worker la prend — visible dans
# Flower / result backend pour distinguer "en attente" de "en cours".
CELERY_TASK_TRACK_STARTED = True

# Recyclage worker pour limiter les fuites mémoire des imports IA + parsing
# PDF (ProjectAIImportService) qui peuvent consommer des centaines de Mo par
# document. Le worker redémarre après N tâches, libérant la RAM.
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(
    os.getenv("CELERY_WORKER_MAX_TASKS_PER_CHILD", "200")
)

# Une tâche IA peut prendre 20-40s ; on borne explicitement pour éviter qu'un
# appel OpenAI bloqué tienne un worker indéfiniment.
# Soft = SIGTERM (la task peut catch), hard = SIGKILL.
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "300"))
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "360"))

# Préfetch limité pour répartir équitablement le travail entre workers,
# notamment pour les tâches longues (IA proposal generation).
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1")
)

# Celery 5.3+: silence le warning au démarrage si Redis n'est pas encore up,
# tente la reconnexion automatique (utile lors d'un déploiement rolling).
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# =========================================================================
# Couche IA (provider hybride) — voir project/services/ai/
# =========================================================================
# Backend actif :
#   - "auto"     : DeepSeek si clé → OpenAI si clé → local → désactivé
#                  (recommandé en prod ; Phase 4 PR17 met DeepSeek en tête)
#   - "deepseek" : force DeepSeek (provider principal DevFlow)
#   - "openai"   : force OpenAI
#   - "local"    : force endpoint local (Ollama, vLLM...)
#   - "none"     : désactive toute IA (heuristiques uniquement)
AI_BACKEND = os.getenv("AI_BACKEND", "auto")

# DeepSeek (Phase 4 — PR17) — provider principal
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
AI_DEEPSEEK_MODEL = os.getenv("AI_DEEPSEEK_MODEL", "deepseek-chat")
AI_DEEPSEEK_BASE_URL = os.getenv(
    "AI_DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1",
)

# OpenAI
AI_OPENAI_MODEL = os.getenv("AI_OPENAI_MODEL", "gpt-4o-mini")
AI_OPENAI_BASE_URL = os.getenv("AI_OPENAI_BASE_URL", "") or None

# Local (compatible OpenAI : Ollama, vLLM, LocalAI, llama.cpp...)
AI_LOCAL_BASE_URL = os.getenv("AI_LOCAL_BASE_URL", "http://localhost:11434/v1")
AI_LOCAL_MODEL = os.getenv("AI_LOCAL_MODEL", "llama3.2:3b")
AI_LOCAL_API_KEY = os.getenv("AI_LOCAL_API_KEY", "ollama")

# Chaîne de fallback en mode AI_BACKEND="auto" — ordre de préférence.
# Valeurs possibles : deepseek, openai, anthropic, claude, local, ollama
# Default : "deepseek,anthropic,local"
#   1. DeepSeek (économique, rapide)
#   2. Anthropic Claude (qualité premium, payant)
#   3. Ollama / Local (gratuit, dernier recours)
AI_FALLBACK_CHAIN = os.getenv("AI_FALLBACK_CHAIN", "deepseek,anthropic,local")

# ── Anthropic Claude (PR-REC-1) ────────────────────────────────────
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-5-20250929")
ANTHROPIC_BASE_URL = os.getenv("ANTHROPIC_BASE_URL", "")

# ── AssemblyAI (PR-REC-2 : transcription audio) ────────────────────
ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY", "")
ASSEMBLYAI_LANGUAGE = os.getenv("ASSEMBLYAI_LANGUAGE", "fr")

# ── Enregistrements de réunion (PR-REC-1) ──────────────────────────
MAX_RECORDING_UPLOAD_MB = int(os.getenv("MAX_RECORDING_UPLOAD_MB", "600"))
SPEAKER_SAMPLE_DURATION_SEC = int(os.getenv("SPEAKER_SAMPLE_DURATION_SEC", "8"))
# Secret pour signer les URLs audio (HMAC). Si vide → fallback sur SECRET_KEY.
RECORDING_AUDIO_TOKEN_SECRET = os.getenv("RECORDING_AUDIO_TOKEN_SECRET", "")
RECORDING_AUDIO_TOKEN_TTL = int(os.getenv("RECORDING_AUDIO_TOKEN_TTL", "1800"))

# ── Storage MinIO/S3 dédié aux recordings (optionnel) ──────────────
# Si MINIO_RECORDINGS_BUCKET est défini, on configure un storage 'recordings'
# qui pointe vers ce bucket. Sinon le fallback est le default storage (local).
MINIO_ENDPOINT = os.getenv("S3_ENDPOINT", "")
MINIO_ACCESS_KEY = os.getenv("S3_ACCESS_KEY", "")
MINIO_SECRET_KEY = os.getenv("S3_SECRET_KEY", "")
MINIO_REGION = os.getenv("S3_REGION", "eu-west-1")
MINIO_RECORDINGS_BUCKET = os.getenv("RECORDING_S3_BUCKET", "")

# Django 4.2+ : configuration unifiée via STORAGES (remplace
# STATICFILES_STORAGE + DEFAULT_FILE_STORAGE). On garde whitenoise
# pour les statics et on ajoute un storage 'recordings' si MinIO/S3
# est configuré ; sinon le default storage Django local est utilisé
# pour les FileField audio (cf. project/models._recording_storage).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if MINIO_RECORDINGS_BUCKET and MINIO_ENDPOINT:
    STORAGES["recordings"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": MINIO_RECORDINGS_BUCKET,
            "endpoint_url": MINIO_ENDPOINT,
            "access_key": MINIO_ACCESS_KEY,
            "secret_key": MINIO_SECRET_KEY,
            "region_name": MINIO_REGION,
            "addressing_style": "path",  # critique pour MinIO
            "signature_version": "s3v4",
            "default_acl": None,         # MinIO ne supporte pas les ACLs
            "file_overwrite": False,
            "querystring_auth": True,
            "object_parameters": {},     # PAS de ServerSideEncryption sur MinIO standalone
        },
    }
# Sinon : _recording_storage() retombera sur le default storage.

# Cache court pour éviter de spammer le LLM (secondes)
AI_CACHE_TTL = int(os.getenv("AI_CACHE_TTL", "300"))
AI_WEB_SEARCH_ENABLED = os.getenv("AI_WEB_SEARCH_ENABLED", "False") == "True"
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "")

# REST Framework / drf-spectacular
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DevFlow API",
    "DESCRIPTION": "API REST DevFlow — projets, budget, IA financière.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# ─────────────────────────────────────────────────────────────────────────
# Channels (WebSocket) — host Redis lu depuis l'env, fallback "redis"
# (nom du service docker-compose) sinon "127.0.0.1" en local.
# ─────────────────────────────────────────────────────────────────────────
_in_docker = os.path.exists("/.dockerenv")
_default_redis_host = "redis" if _in_docker else "127.0.0.1"
CHANNELS_REDIS_HOST = os.getenv("CHANNELS_REDIS_HOST") or os.getenv("REDIS_HOST", _default_redis_host)
CHANNELS_REDIS_PORT = int(os.getenv("CHANNELS_REDIS_PORT") or os.getenv("REDIS_PORT", 6379))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(CHANNELS_REDIS_HOST, CHANNELS_REDIS_PORT)],
        },
    },
}
# =========================
# EMAIL CONFIG
# =========================
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = os.getenv("EMAIL_HOST")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
# SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.hostinger.com")
EMAIL_PORT = config("EMAIL_PORT", default=465, cast=int)
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
# =========================
# DJANGO ALLAUTH - VERSION RÉCENTE
# =========================
ACCOUNT_ADAPTER = "project.adapters.AccountAdapter"

ACCOUNT_FORMS = {
    "signup": "project.forms.CustomSignupForm",
}

ACCOUNT_LOGIN_METHODS = {"email"}


ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = False

ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/5m",
}

LOGIN_REDIRECT_URL = "/dashboard/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[DevFlow]"