"""
Django settings for parcelaireKG project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-9uzaef-rpxlqoxg!juy_7x3z*a9!y7%mhtajqaamyp9x(#0qr8'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'www.flow.datarium-dev.com',
    'flow.datarium-dev.com',
    'localhost',
    '127.0.0.1'
]
CSRF_TRUSTED_ORIGINS=[
    'https://flow.datarium-dev.com',
    'http://flow.datarium-dev.com',
]
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.gis',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_framework',
    'rest_framework.authtoken',
    'import_export',
    'mathfilters',
    'django_select2',
    'djmoney',
    'tinymce',
    # 'simple_history',
    # 'num2words',
    'django_filters',
    # 'qr_code',
    # 'notifications',
    "channels",
    'weasyprint',
    "csp",
    'drf_spectacular',
    'corsheaders',
    "project",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'ProjectFlow.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.context_processors.devflow_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectFlow.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
SITE_ID = 1

USE_THOUSAND_SEPARATOR=True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BEAT_SCHEDULE = {
    # Balayage de toutes les tâches DevFlow 2x/jour pour envoyer
    # automatiquement des relances aux assignees et notifier les PM.
    # Heures locales : 9h00 (matin) et 16h00 (après-midi) Africa/Abidjan.
    "task-reminder-morning-sweep": {
        "task": "project.tasks.run_task_reminder_sweep",
        "schedule": crontab(hour=9, minute=0),
    },
    "task-reminder-afternoon-sweep": {
        "task": "project.tasks.run_task_reminder_sweep",
        "schedule": crontab(hour=16, minute=0),
    },
}

# Paramètres du moteur de relance (surchargeable via env)
TASK_REMINDER_COOLDOWN_HOURS = int(os.getenv("TASK_REMINDER_COOLDOWN_HOURS", "10"))
TASK_STALE_DAYS = int(os.getenv("TASK_STALE_DAYS", "2"))
TASK_DUE_SOON_DAYS = int(os.getenv("TASK_DUE_SOON_DAYS", "3"))

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Abidjan"


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# =========================================================================
# Couche IA (provider hybride) — voir project/services/ai/
# =========================================================================
# Backend actif :
#   - "auto"   : OpenAI si clé dispo, sinon endpoint local, sinon désactivé
#   - "openai" : force OpenAI
#   - "local"  : force endpoint local (Ollama, vLLM...)
#   - "none"   : désactive toute IA (heuristiques uniquement)
AI_BACKEND = os.getenv("AI_BACKEND", "auto")

# OpenAI
AI_OPENAI_MODEL = os.getenv("AI_OPENAI_MODEL", "gpt-4o-mini")
AI_OPENAI_BASE_URL = os.getenv("AI_OPENAI_BASE_URL", "") or None

# Local (compatible OpenAI : Ollama, vLLM, LocalAI, llama.cpp...)
AI_LOCAL_BASE_URL = os.getenv("AI_LOCAL_BASE_URL", "http://localhost:11434/v1")
AI_LOCAL_MODEL = os.getenv("AI_LOCAL_MODEL", "mistral:7b")
AI_LOCAL_API_KEY = os.getenv("AI_LOCAL_API_KEY", "ollama")

# Cache court pour éviter de spammer le LLM (secondes)
AI_CACHE_TTL = int(os.getenv("AI_CACHE_TTL", "300"))

# REST Framework / drf-spectacular
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DevFlow API",
    "DESCRIPTION": "API REST DevFlow — projets, budget, IA financière.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}