# Generated by Django 4.2.30 on 2026-04-09 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(choices=[('HOURLY', 'Horaire'), ('DAILY', 'Journalier'), ('MONTHLY', 'Mensuel')], default='DAILY', max_length=10)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_internal_cost', models.BooleanField(default=True)),
                ('is_billable_rate', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to='project.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('HUMAN', 'Ressources humaines'), ('SOFTWARE', 'Logiciels / Licences'), ('INFRA', 'Infrastructure / Cloud'), ('EQUIPMENT', 'Équipements'), ('SUBCONTRACT', 'Sous-traitance'), ('TRAVEL', 'Déplacements'), ('TRAINING', 'Formation'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#7C6FF7', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_unit', models.CharField(blank=True, max_length=10)),
                ('rate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('computed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('billing_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_snapshots', to='project.billingrate')),
                ('timesheet_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshot', to='project.timesheetentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_type', models.CharField(choices=[('FIXED', 'Forfait'), ('MILESTONE', 'Paiement jalon'), ('TIME_MATERIAL', 'Temps passé'), ('LICENSE', 'Licence'), ('OTHER', 'Autre')], default='FIXED', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='project.project')),
            ],
            options={
                'ordering': ['expected_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='DRAFT', max_length=15)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='project.costcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_expenses', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='project.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='project.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='project.sprint')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='project.task')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_project_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manuel'), ('TASK', 'Tâche'), ('SPRINT', 'Sprint'), ('MILESTONE', 'Jalon')], default='MANUAL', max_length=20)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='project.costcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimate_lines', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='project.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='project.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='project.sprint')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='project.task')),
            ],
            options={
                'ordering': ['project', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('REVISED', 'Révisé'), ('CLOSED', 'Clos')], default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_software_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_infra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_subcontract_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contingency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_margin_percent', models.PositiveSmallIntegerField(default=20)),
                ('planned_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('alert_threshold_percent', models.PositiveSmallIntegerField(default=80)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budgetestimatif', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
