# Generated by Django 4.2.30 on 2026-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_billingrate_costcategory_timesheetcostsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingrate',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Tarif de facturation', 'verbose_name_plural': 'Tarifs de facturation'},
        ),
        migrations.RenameField(
            model_name='projectestimateline',
            old_name='estimated_amount',
            new_name='cost_amount',
        ),
        migrations.RenameField(
            model_name='projectestimateline',
            old_name='unit_cost',
            new_name='cost_unit_amount',
        ),
        migrations.RemoveField(
            model_name='billingrate',
            name='rate_amount',
        ),
        migrations.AddField(
            model_name='billingrate',
            name='cost_rate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='sale_rate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='worker_level',
            field=models.CharField(choices=[('INTERN', 'Stagiaire'), ('JUNIOR', 'Junior'), ('MID', 'Intermédiaire'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('EXPERT', 'Expert'), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectestimateline',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='projectestimateline',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectestimateline',
            name='sale_unit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='is_billable_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='name',
            field=models.CharField(blank=True, help_text='Nom libre si le tarif ne vise ni un utilisateur ni une équipe.', max_length=120),
        ),
    ]
