# Generated by Django 4.2.30 on 2026-04-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_billingrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('seniority', models.CharField(choices=[('INTERN', 'Stagiaire'), ('JUNIOR', 'Junior'), ('MID', 'Intermédiaire'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('EXPERT', 'Expert')], default='JUNIOR', max_length=20)),
                ('contract_type', models.CharField(choices=[('FULL_TIME', 'Temps plein'), ('PART_TIME', 'Temps partiel'), ('FREELANCE', 'Freelance'), ('INTERN', 'Stage')], default='FULL_TIME', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='devflow/users/avatars/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('capacity_hours_per_day', models.DecimalField(decimal_places=2, default=8, help_text='Capacité théorique par jour', max_digits=5)),
                ('capacity_hours_per_week', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('availability_percent', models.PositiveSmallIntegerField(default=100, help_text='Disponibilité actuelle (%)')),
                ('cost_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Coût interne journalier', max_digits=14)),
                ('billable_rate_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Tarif de vente journalier', max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('performance_score', models.PositiveSmallIntegerField(default=0)),
                ('velocity_contribution', models.PositiveIntegerField(default=0)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_company_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='project.workspace')),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
