# Generated by Django 4.2.30 on 2026-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': [('view_financial_data', 'Peut voir les données financières des projets')]},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
