# Generated by Django 4.2.30 on 2026-04-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options_alter_workspace_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrevenue',
            name='is_received',
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='management_reserve_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='overhead_cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='committed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='is_direct_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='is_labor_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='invoiced_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Prévu'), ('INVOICED', 'Facturé'), ('PARTIALLY_PAID', 'Partiellement encaissé'), ('PAID', 'Encaissé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ESTIMATED', 'Estimatif'), ('BASELINE', 'Prévisionnel validé'), ('APPROVED', 'Approuvé'), ('REVISED', 'Révisé'), ('CLOSED', 'Clos')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='status',
            field=models.CharField(choices=[('ESTIMATED', 'Estimatif'), ('FORECAST', 'Prévisionnel'), ('COMMITTED', 'Engagé'), ('ACCRUED', 'Constaté'), ('PAID', 'Décaissé'), ('REJECTED', 'Rejeté')], default='ESTIMATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectrevenue',
            name='revenue_type',
            field=models.CharField(choices=[('FIXED', 'Forfait'), ('MILESTONE', 'Paiement jalon'), ('TIME_MATERIAL', 'Régie'), ('LICENSE', 'Licence'), ('OTHER', 'Autre')], default='FIXED', max_length=20),
        ),
    ]
