# Generated by Django 4.2.30 on 2026-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_projectrevenue_is_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectestimateline',
            options={'ordering': ['project', 'budget_stage', 'label']},
        ),
        migrations.AddField(
            model_name='projectestimateline',
            name='budget_stage',
            field=models.CharField(choices=[('ESTIMATED', 'Estimatif'), ('BASELINE', 'Prévisionnel validé'), ('FORECAST', 'Forecast'), ('RAF', 'Reste à faire')], default='ESTIMATED', max_length=20),
        ),
    ]
