# Generated by Django 4.2.30 on 2026-04-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectestimateline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=15),
        ),
    ]
