# Generated by Django 4.2.30 on 2026-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_timesheetentry_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrevenue',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
