# Generated by Django 4.2.30 on 2026-04-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectrevenue_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='status',
            field=models.CharField(choices=[('ESTIMATED', 'Estimatif'), ('FORECAST', 'Prévisionnel'), ('COMMITTED', 'Engagé'), ('ACCRUED', 'Constaté'), ('PAID', 'Décaissé'), ('REJECTED', 'Rejeté'), ('DRAFT', 'Brouillon'), ('VALIDATED', 'Approuvé')], default='ESTIMATED', max_length=15),
        ),
    ]
