# Generated by Django 4.2.30 on 2026-04-16 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_alter_projectexpense_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexpense',
            options={'ordering': ['-expense_date', '-created_at'], 'permissions': [('approve_projectexpense_level1', 'Peut valider une dépense au niveau 1'), ('approve_projectexpense_level2', 'Peut valider une dépense au niveau 2'), ('view_projectexpense_financial', 'Peut voir les dépenses projet')]},
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='approval_state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('LEVEL1_APPROVED', 'Validé niveau 1'), ('LEVEL2_APPROVED', 'Validé niveau 2'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_approved_project_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='level2_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='level2_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_approved_project_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_project_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ESTIMATED', 'Estimatif'), ('FORECAST', 'Prévisionnel'), ('COMMITTED', 'Engagé'), ('ACCRUED', 'Constaté'), ('PAID', 'Décaissé'), ('REJECTED', 'Rejeté'), ('VALIDATED', 'Validé')], default='DRAFT', max_length=20),
        ),
    ]
