# Generated by Django 4.2.30 on 2026-04-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_alter_projectexpense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='project.sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectModuleROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=160)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roi_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_rois', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_text', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('module_name', models.CharField(blank=True, max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='devflow/project_imports/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploadé'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec')], default='UPLOADED', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_imports', to='project.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_imports', to='project.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roi_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('backlog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='project.backlogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
