# Generated by Django 4.2.30 on 2026-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_sprintfinancialsnapshot_projectmoduleroi_projectkpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devflow/projects/covers/'),
        ),
    ]
