# Generated by Django 4.2.30 on 2026-04-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('is_billable', models.BooleanField(default=False)),
                ('budget_type', models.CharField(choices=[('FIXED', 'Forfait'), ('TIME', 'Temps passé'), ('NONE', 'Non facturé')], default='TIME', max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.projectcategory'),
        ),
    ]
