# Generated by Django 4.2.30 on 2026-04-26 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0014_projectcategory_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAIProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de génération'), ('GENERATING', 'Génération en cours'), ('READY', 'Prête à validation'), ('PARTIALLY_VALIDATED', 'Partiellement validée'), ('VALIDATED', 'Validée'), ('APPLIED', 'Appliquée au projet'), ('REJECTED', 'Rejetée'), ('FAILED', 'Échec de génération')], default='PENDING', max_length=25)),
                ('used_provider', models.CharField(blank=True, max_length=50)),
                ('used_model', models.CharField(blank=True, max_length=120)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('risks_summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='project.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_proposals', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_ai_proposals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='project.workspace')),
            ],
            options={
                'verbose_name': 'Proposition IA projet',
                'verbose_name_plural': 'Propositions IA projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='affects_revenue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_strategic',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectAIProposalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('TRIGGERED', 'Déclenchée'), ('GENERATED', 'Générée'), ('ITEM_EDITED', 'Item modifié'), ('ITEM_VALIDATED', 'Item validé'), ('ITEM_REJECTED', 'Item rejeté'), ('VALIDATED', 'Proposition validée'), ('APPLIED', 'Proposition appliquée'), ('REJECTED', 'Proposition rejetée'), ('FAILED', 'Échec')], max_length=25)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_proposal_actions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project.projectaiproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAIProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ROADMAP_ITEM', 'Phase roadmap'), ('MILESTONE', 'Jalon'), ('SPRINT', 'Sprint'), ('BACKLOG', 'Élément de backlog'), ('TASK', 'Tâche'), ('DEPENDENCY', 'Dépendance'), ('ASSIGNMENT', 'Affectation')], max_length=20)),
                ('item_status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('EDITED', 'Modifié'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('APPLIED', 'Appliqué')], default='PROPOSED', max_length=15)),
                ('local_ref', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('complexity', models.CharField(blank=True, max_length=20)),
                ('estimate_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recommended_profile', models.CharField(blank=True, max_length=120)),
                ('sprint_ref', models.CharField(blank=True, max_length=80)),
                ('milestone_ref', models.CharField(blank=True, max_length=80)),
                ('depends_on_refs', models.JSONField(blank=True, default=list)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('velocity_target', models.PositiveIntegerField(default=0)),
                ('extra_payload', models.JSONField(blank=True, default=dict)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('applied_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_object_model', models.CharField(blank=True, max_length=80)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_ai_proposal_items', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project.projectaiproposal')),
                ('recommended_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposal', 'kind', 'order_index'],
                'indexes': [models.Index(fields=['proposal', 'kind'], name='project_pro_proposa_a97f05_idx'), models.Index(fields=['proposal', 'item_status'], name='project_pro_proposa_1d0ec7_idx')],
            },
        ),
    ]
