# Generated by Django 4.2.30 on 2026-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_projectcategory_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='affects_revenue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_strategic',
            field=models.BooleanField(default=False),
        ),
    ]
