# Generated by Django 4.2.30 on 2026-04-27 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0015_projectaiproposal_projectcategory_affects_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('OVERDUE', 'Tâche en retard'), ('STALE', 'Tâche stagnante'), ('DUE_SOON', 'Échéance proche'), ('BLOCKED', 'Tâche bloquée')], default='STALE', max_length=20)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'Notification in-app'), ('BOTH', 'Email + in-app')], default='BOTH', max_length=10)),
                ('task_status_at_send', models.CharField(blank=True, max_length=20)),
                ('task_due_date_at_send', models.DateField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_status_change', models.BooleanField(default=False, help_text="Vrai si l'assignee a mis à jour la tâche après ce rappel.")),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='project.task')),
            ],
            options={
                'verbose_name': 'Rappel tâche',
                'verbose_name_plural': 'Rappels tâches',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['task', '-sent_at'], name='project_tas_task_id_147271_idx'), models.Index(fields=['recipient', '-sent_at'], name='project_tas_recipie_15e510_idx')],
            },
        ),
    ]
