# Generated by Django 4.2.30 on 2026-04-29 18:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_workspace_letterhead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='project_inv_workspa_6008b5_idx',
            old_name='proj_inv_ws_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='project_inv_project_a12c46_idx',
            old_name='proj_inv_proj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='project_inv_due_dat_30d9eb_idx',
            old_name='proj_inv_due_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Auto-généré si non renseigné (FAC-AAAA-NNNN).', max_length=40),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Taux de TVA en % appliqué globalement (par défaut 18%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceclient',
            name='tax_id',
            field=models.CharField(blank=True, help_text='N° TVA / NIF / SIRET / autre identifiant fiscal.', max_length=60),
        ),
    ]
