# Generated by Django 4.2.30 on 2026-04-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_rename_proj_inv_ws_status_idx_project_inv_workspa_6008b5_idx_and_more'),
        ('project', '0021_task_period_and_expired'),
    ]

    operations = [
    ]
