# Generated by Django 4.2.30 on 2026-04-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_merge_20260429_1915'),
        ('project', '0022_project_teams_m2m'),
    ]

    operations = [
    ]
