# Generated by Django 4.2.30 on 2026-05-30 12:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0026_phase2_multimode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgetForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horizon_end', models.DateField()),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('optimistic_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('pessimistic_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expected_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expected_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('overrun_risk_percent', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(default='medium', help_text='low / medium / high', max_length=10)),
                ('used_provider', models.CharField(default='heuristic', max_length=30)),
                ('used_model', models.CharField(blank=True, max_length=80)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('BASELINE', 'Baseline (référence)'), ('FORECAST', 'Forecast (projection)'), ('MANUAL', 'Snapshot manuel'), ('AUTO', 'Snapshot automatique')], db_index=True, default='MANUAL', max_length=20)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payload', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='billingrate',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Si renseigné, ce tarif ne s'applique qu'à ce projet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_rates', to='project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='computed_cost_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Écart entre baseline et forecast (positif = dépassement).', max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='computed_eac',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Estimate at Completion : coût total prévu à la fin du projet.', max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='eac_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admincase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='mapped_status',
            field=models.CharField(blank=True, choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'Review'), ('DONE', 'Terminé'), ('BLOCKED', 'Bloqué'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expirée non traitée')], help_text='Statut Task auquel cette colonne correspond.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fieldreportphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectviewpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='realestatelot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['user', 'project', '-valid_from'], name='billing_user_proj_idx'),
        ),
        migrations.AddField(
            model_name='projectbudgetsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudgetsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_snapshots', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectbudgetsnapshot',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_snapshots', to='project.workspace'),
        ),
        migrations.AddField(
            model_name='projectbudgetforecastrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_forecast_runs', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectbudgetforecastrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_forecast_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudgetforecastrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_forecast_runs', to='project.workspace'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetsnapshot',
            index=models.Index(fields=['project', '-snapshot_date'], name='snap_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetsnapshot',
            index=models.Index(fields=['project', 'kind'], name='snap_proj_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetforecastrun',
            index=models.Index(fields=['project', '-created_at'], name='forecast_proj_date_idx'),
        ),
    ]
