# Generated by Django 4.2.30 on 2026-05-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_projectbudgetforecastrun_projectbudgetsnapshot_and_more'),
        ('project', '0030_phase5_ai_reports'),
    ]

    operations = [
    ]
