# Generated by Django 4.2.30 on 2026-06-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_merge_20260530_2100'),
        ('project', '0032_security_audit_log'),
    ]

    operations = [
    ]
