# Generated by Django 4.2.30 on 2026-10-06 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0050_seed_more_methodologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingdecision',
            options={'ordering': ['-decided_at', '-id'], 'verbose_name': 'Décision de réunion', 'verbose_name_plural': 'Décisions de réunion'},
        ),
        migrations.AlterModelOptions(
            name='meetingrecording',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enregistrement de réunion', 'verbose_name_plural': 'Enregistrements de réunion'},
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='project_aia_workspa_7fcd8c_idx',
            old_name='proj_aial_ws_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='project_aia_project_07848b_idx',
            old_name='proj_aial_proj_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='project_aia_user_id_945e2d_idx',
            old_name='proj_aial_usr_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='project_aia_tool_na_dce697_idx',
            old_name='proj_aial_tool_st_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedspeaker',
            new_name='project_det_recordi_137e75_idx',
            old_name='detected_spk_confirmed_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingagendaitem',
            new_name='project_mee_meeting_3d913c_idx',
            old_name='proj_agenda_meet_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingagendaitem',
            new_name='project_mee_meeting_b9a0ec_idx',
            old_name='proj_agenda_meet_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdecision',
            new_name='project_mee_workspa_8cf411_idx',
            old_name='decision_ws_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdecision',
            new_name='project_mee_workspa_2a3ad8_idx',
            old_name='decision_ws_date_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingfollowup',
            new_name='project_mee_meeting_23d24b_idx',
            old_name='meet_followup_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingminutesversion',
            new_name='project_mee_meeting_115b5d_idx',
            old_name='minutes_ver_meet_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingparticipation',
            new_name='project_mee_meeting_9f62a3_idx',
            old_name='proj_meet_p_meet_rsvp_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingparticipation',
            new_name='project_mee_meeting_e8550b_idx',
            old_name='proj_meet_p_meet_att_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingprojectreview',
            new_name='project_mee_meeting_36c457_idx',
            old_name='meet_review_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingprojectreview',
            new_name='project_mee_project_121acd_idx',
            old_name='meet_review_proj_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingrecording',
            new_name='project_mee_workspa_a9582f_idx',
            old_name='recording_ws_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingrecording',
            new_name='project_mee_meeting_2b3a6d_idx',
            old_name='recording_meet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingseries',
            new_name='project_mee_workspa_3fcf0f_idx',
            old_name='meeting_ser_ws_active_idx',
        ),
        migrations.RenameIndex(
            model_name='methodology',
            new_name='project_met_workspa_f24956_idx',
            old_name='proj_method_ws_active_idx',
        ),
        migrations.RenameIndex(
            model_name='methodology',
            new_name='project_met_family_23d08a_idx',
            old_name='proj_method_fam_active_idx',
        ),
        migrations.RenameIndex(
            model_name='methodologystatus',
            new_name='project_met_methodo_b4fc88_idx',
            old_name='proj_status_meth_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='methodologystatus',
            new_name='project_met_methodo_f7b229_idx',
            old_name='proj_status_meth_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='methodologyworkflow',
            new_name='project_met_methodo_0fcb22_idx',
            old_name='proj_workflow_meth_at_idx',
        ),
        migrations.RenameIndex(
            model_name='projectartifact',
            new_name='project_pro_project_ef48e9_idx',
            old_name='proj_art_proj_code_idx',
        ),
        migrations.RenameIndex(
            model_name='projectartifact',
            new_name='project_pro_project_3c9217_idx',
            old_name='proj_art_proj_cur_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttemplate',
            new_name='project_pro_sector_5e6c56_idx',
            old_name='proj_tmpl_sec_act_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttemplate',
            new_name='project_pro_methodo_f008f2_idx',
            old_name='proj_tmpl_meth_act_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingaiextraction',
            new_name='project_rec_recordi_dacdec_idx',
            old_name='ai_extract_rec_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='speakerparticipantmapping',
            new_name='project_spe_recordi_b70402_idx',
            old_name='spk_map_rec_active_idx',
        ),
        migrations.RenameIndex(
            model_name='speakersegment',
            new_name='project_spe_recordi_15e989_idx',
            old_name='segment_rec_label_idx',
        ),
        migrations.RenameIndex(
            model_name='speakersegment',
            new_name='project_spe_recordi_320372_idx',
            old_name='segment_rec_start_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtransition',
            new_name='project_wor_workflo_75e8d4_idx',
            old_name='proj_trans_wf_auto_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacevoiceprint',
            new_name='project_wor_workspa_30ad23_idx',
            old_name='voiceprint_ws_seen_idx',
        ),
        migrations.AlterField(
            model_name='aiactionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiactionlog',
            name='user_message',
            field=models.TextField(blank=True, help_text='Le message original du user qui a déclenché ce call.'),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiusagequota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='sample_audio',
            field=models.FileField(blank=True, help_text="Extrait MP3 ~8s pour identification à l'oreille.", max_length=600, null=True, storage=project.models._recording_storage, upload_to=project.models._speaker_sample_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projet associé. Facultatif : une facture peut être émise librement (consulting flat-fee, licence, frais divers...). La facture reste toujours rattachée à un workspace.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='project.project'),
        ),
        migrations.AlterField(
            model_name='meetingagendaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingdecision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingdecision',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text="Réunion à l'origine de la décision (peut être null si décision hors réunion).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_decisions', to='project.projectmeeting'),
        ),
        migrations.AlterField(
            model_name='meetingdecision',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projets impactés par cette décision.', related_name='meeting_decisions', to='project.project'),
        ),
        migrations.AlterField(
            model_name='meetingfollowup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingminutesversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingminutesversion',
            name='source',
            field=models.CharField(default='manual', help_text='manual | ai_regenerate | ai_initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='achievements',
            field=models.TextField(blank=True, help_text='Réalisations / avancées depuis la dernière revue.'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='actions_to_take',
            field=models.TextField(blank=True, help_text='Actions à mener avant la prochaine revue, format libre ou puces (- action @qui — pour quand).'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='blockers',
            field=models.TextField(blank=True, help_text='Points bloquants / risques identifiés.'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='decisions',
            field=models.TextField(blank=True, help_text='Décisions prises pendant la réunion concernant ce projet.'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='next_milestone',
            field=models.CharField(blank=True, help_text='Prochain jalon attendu (texte libre).', max_length=200),
        ),
        migrations.AlterField(
            model_name='meetingprojectreview',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Avancement en % à la date de la revue (0-100).'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Fichier audio brut (webm/opus/mp3/wav).', max_length=600, null=True, storage=project.models._recording_storage, upload_to=project.models._audio_upload_path),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='consent_acknowledged',
            field=models.BooleanField(default=False, help_text="L'organisateur a confirmé avoir informé les participants."),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='final_transcript',
            field=models.TextField(blank=True, help_text='Transcript final avec noms réels des speakers (post-mapping).'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='summary_markdown',
            field=models.TextField(blank=True, help_text="Compte-rendu structuré (Markdown) généré par l'IA."),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='default_agenda',
            field=models.TextField(blank=True, help_text='Ordre du jour par défaut (peut être édité par occurrence).'),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='default_participants',
            field=models.ManyToManyField(blank=True, help_text='Participants invités automatiquement à chaque occurrence.', related_name='default_meeting_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='default_projects',
            field=models.ManyToManyField(blank=True, help_text="Projets pré-renseignés en revue à chaque occurrence. Permet le scénario 'Comité hebdo : on passe TOUS les projets en revue'.", related_name='default_meeting_series', to='project.project'),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Si False, la génération auto cesse mais l'historique reste."),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Couleur hex pour la pastille (#1d4ed8...).', max_length=7),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text="Bag de settings : { 'has_sprints': true, 'has_phases': false, 'has_wip_limits': true, 'requires_estimation': true, ... }"),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe FontAwesome ou nom court (ex : 'fa-flag-checkered').", max_length=50),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True = fournie par DevFlow, non modifiable.'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='NULL = méthodologie système (visible par tous les workspaces).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='project.workspace'),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Liste de capacités/tools déclarées (ex : ['create_backlog', 'estimate_stories'])."),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text="Few-shot examples : [{'user': '...', 'assistant': '...'}]."),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='persona',
            field=models.CharField(help_text="Une phrase pour décrire la personnalité (ex : 'Scrum Master virtuel agile et bienveillant').", max_length=200),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='system_prompt',
            field=models.TextField(help_text='Prompt système complet (instructions, format, ton).'),
        ),
        migrations.AlterField(
            model_name='methodologyaiprofile',
            name='tone',
            field=models.CharField(blank=True, help_text="Ton recommandé (ex : 'directive', 'coach', 'analytical').", max_length=30),
        ),
        migrations.AlterField(
            model_name='methodologyartifact',
            name='ai_prompt_key',
            field=models.CharField(help_text='Clé du AIPromptTemplate à utiliser pour générer ce doc.', max_length=80),
        ),
        migrations.AlterField(
            model_name='methodologyartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyartifact',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="True = artefact mis en avant dans l'UI projet."),
        ),
        migrations.AlterField(
            model_name='methodologyceremony',
            name='default_duration_min',
            field=models.PositiveIntegerField(default=30, help_text='Durée standard en minutes.'),
        ),
        migrations.AlterField(
            model_name='methodologyceremony',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyceremony',
            name='required_role_codes',
            field=models.JSONField(blank=True, default=list, help_text="Rôles obligatoirement présents (ex : ['scrum_master', 'po'])."),
        ),
        migrations.AlterField(
            model_name='methodologyceremony',
            name='template_agenda',
            field=models.TextField(blank=True, help_text='Ordre du jour template (markdown).'),
        ),
        migrations.AlterField(
            model_name='methodologykpi',
            name='compute_strategy',
            field=models.CharField(help_text="Identifiant de la stratégie de calcul (ex : 'velocity').", max_length=80),
        ),
        migrations.AlterField(
            model_name='methodologykpi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologykpi',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='True = KPI affiché en gros / en haut du dashboard.'),
        ),
        migrations.AlterField(
            model_name='methodologykpi',
            name='unit',
            field=models.CharField(blank=True, help_text="Ex : 'story_points', 'days', '%', 'tickets'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='methodologyrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyrole',
            name='is_required',
            field=models.BooleanField(default=False, help_text='True = le projet ne peut pas démarrer sans ce rôle pourvu.'),
        ),
        migrations.AlterField(
            model_name='methodologyrole',
            name='max_holders',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre maximum de titulaires (Scrum Master = 1, Dev = N).', null=True),
        ),
        migrations.AlterField(
            model_name='methodologyrole',
            name='suggested_rbac_role',
            field=models.CharField(blank=True, help_text="Rôle RBAC suggéré (ex : 'project_manager').", max_length=50),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='code',
            field=models.SlugField(help_text="Identifiant local à la méthodologie (ex : 'in_review')."),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='color',
            field=models.CharField(blank=True, help_text="#hex pour le badge dans l'UI.", max_length=7),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='is_final',
            field=models.BooleanField(default=False, help_text="True = statut terminal (compte pour 'completed')."),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='is_initial',
            field=models.BooleanField(default=False, help_text="True = statut par défaut à la création d'un objet."),
        ),
        migrations.AlterField(
            model_name='methodologystatus',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Limite WIP (Kanban). Null = pas de limite.', null=True),
        ),
        migrations.AlterField(
            model_name='methodologyworkflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodologyworkflow',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Workflow par défaut pour cette catégorie d'objet."),
        ),
        migrations.AlterField(
            model_name='notificationdigest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectaireport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectartifact',
            name='file',
            field=models.FileField(blank=True, help_text='Pour les artefacts binaires (docx, pdf, csv).', null=True, upload_to='devflow/artifacts/'),
        ),
        migrations.AlterField(
            model_name='projectartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectartifact',
            name='is_current',
            field=models.BooleanField(default=True, help_text='True = version courante affichée. False = historique.'),
        ),
        migrations.AlterField(
            model_name='projectmeeting',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projets passés en revue dans cette réunion (comité, revue, etc.).', related_name='committee_meetings', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectmeeting',
            name='series',
            field=models.ForeignKey(blank=True, help_text="Si l'occurrence vient d'une série récurrente.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='project.meetingseries'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='default_milestones',
            field=models.JSONField(blank=True, default=list, help_text="[{'name': 'Validation cadrage', 'offset_days': 15}]"),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='default_phases',
            field=models.JSONField(blank=True, default=list, help_text="[{'name': 'Étude', 'duration_days': 15, 'description': '...'}]"),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='default_risks',
            field=models.JSONField(blank=True, default=list, help_text="[{'title': '...', 'category': '...', 'probability': 3, 'impact': 4}]"),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='default_tasks',
            field=models.JSONField(blank=True, default=list, help_text="[{'title': '...', 'phase': '...', 'duration_days': 5}]"),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='estimated_duration_days',
            field=models.PositiveIntegerField(default=90, help_text='Durée typique en jours pour un projet de ce template.'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='methodology',
            field=models.ForeignKey(blank=True, help_text='Méthodologie par défaut appliquée à partir de ce template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='project.methodology'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='sub_sector',
            field=models.CharField(blank=True, help_text="Ex : 'ERP', 'Mobile App', 'Bâtiment', 'Hôpital'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='recordingaiextraction',
            name='assignee_hint',
            field=models.CharField(blank=True, help_text="Nom détecté par l'IA (à matcher à un User si possible).", max_length=120),
        ),
        migrations.AlterField(
            model_name='recordingaiextraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordingaiextraction',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text="L'utilisateur a confirmé cette extraction."),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speakerparticipantmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='speaker_label',
            field=models.CharField(help_text="Label brut diarisé (ex: 'SPEAKER_00', 'A', 'B').", max_length=40),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='conditions_json',
            field=models.JSONField(blank=True, default=dict, help_text="Conditions structurées vérifiées au runtime (ex : {'min_estimate': 1, 'requires_assignee': true})."),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='label',
            field=models.CharField(blank=True, help_text="Libellé du bouton (ex : 'Démarrer', 'Soumettre à revue').", max_length=80),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='required_role_codes',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes de MethodologyRole autorisés (ex : ['po', 'sm']). Vide = tout user du projet."),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='requires_comment',
            field=models.BooleanField(default=False, help_text="True = l'utilisateur doit saisir un commentaire pour transitionner."),
        ),
        migrations.AlterField(
            model_name='workspaceroleassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workspacevoiceprint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
