# Generated by Django 4.2.30 on 2026-10-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0051_sync_model_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures prévues pour cette ligne (planification).', max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager direct (N+1), dans le même workspace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='project.userprofile'),
        ),
        migrations.CreateModel(
            name='TimesheetReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DAILY_MISSING', 'Relance quotidienne'), ('WEEKLY_INCOMPLETE', 'Semaine incomplète'), ('WEEKLY_MISSING', 'Aucun timesheet (critique)'), ('WEEKLY_REPORT_MANAGER', 'Rapport hebdo N+1'), ('WEEKLY_REPORT_TOP', 'Rapport hebdo direction')], max_length=24)),
                ('period_start', models.DateField()),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_reminder_logs', to='project.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('action', models.CharField(choices=[('SUBMITTED', 'Soumise'), ('APPROVED', 'Validée'), ('REJECTED', 'Rejetée'), ('REOPENED', 'Rouverte')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_actions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approval_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approval_logs', to='project.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='timesheetreminderlog',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'kind', 'period_start'), name='uniq_timesheet_reminder'),
        ),
        migrations.AddIndex(
            model_name='timesheetapprovallog',
            index=models.Index(fields=['workspace', 'employee', 'week_start'], name='ts_log_ws_emp_week_idx'),
        ),
    ]
