# Generated by Django 4.2.30 on 2026-10-06 23:45

from django.db import migrations, models
import django.db.models.deletion


def backfill_direct_messages(apps, schema_editor):
    """Marque les DM historiques (« DM @a / @b », 2 membres) et pose leur dm_key."""
    Channel = apps.get_model("project", "DirectChannel")
    Membership = apps.get_model("project", "ChannelMembership")
    seen = set()
    for channel in Channel.objects.filter(is_private=True, name__startswith="DM @").order_by("id"):
        user_ids = sorted(Membership.objects.filter(channel_id=channel.id).values_list("user_id", flat=True))
        if len(user_ids) != 2:
            continue
        key = f"{user_ids[0]}:{user_ids[1]}"
        channel.kind = "DM"
        if (channel.workspace_id, key) not in seen:  # doublons historiques : seul le plus ancien est la référence
            channel.dm_key = key
            seen.add((channel.workspace_id, key))
        channel.save(update_fields=["kind", "dm_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_team_hierarchy_timesheet_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchannel',
            name='dm_key',
            field=models.CharField(blank=True, help_text='« <user_id_min>:<user_id_max> » pour les DM (unicité par paire).', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='directchannel',
            name='kind',
            field=models.CharField(choices=[('DM', 'Message direct'), ('TEAM', 'Équipe'), ('PROJECT', 'Projet'), ('GROUP', 'Groupe')], db_index=True, default='GROUP', max_length=10),
        ),
        migrations.AddField(
            model_name='directchannel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='project.project'),
        ),
        migrations.AddField(
            model_name='directchannel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='project.team'),
        ),
        migrations.RunPython(backfill_direct_messages, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='directchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('dm_key__isnull', False)), fields=('workspace', 'dm_key'), name='uniq_chat_dm_pair'),
        ),
        migrations.AddConstraint(
            model_name='directchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team',), name='uniq_chat_team_channel'),
        ),
        migrations.AddConstraint(
            model_name='directchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project',), name='uniq_chat_project_channel'),
        ),
    ]
